version: '3'

services:
  app:
    build: .
#    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    container_name: fin-api
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    networks:
      - fin-network

  db:
    build: ./.docker/mysql
    container_name: fin-api-db
    tty: true
#    restart: always
    ports:
      - 53306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fin-api
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fin-network

networks:
  fin-network:
    driver: bridge
